	// Xn  =   0.0f, Yn  =   0.0, Zn  =   0.0;
	F32_opMov,     const_F0_0, 0, Xn,
	F32_opMov,     const_F0_0, 0, Yn,
	F32_opMov,     const_F0_0, 0, Zn,
	// Xn2 =   0.0f, Yn2 =   0.0, Zn2 =   0.0;
	F32_opMov,     const_F0_0, 0, Xn2,
	F32_opMov,     const_F0_0, 0, Yn2,
	F32_opMov,     const_F0_0, 0, Zn2,
	// Xn3 =   0.0f, Yn3 =   0.0, Zn3 =   0.0;
	F32_opMov,     const_F0_0, 0, Xn3,
	F32_opMov,     const_F0_0, 0, Yn3,
	F32_opMov,     const_F0_0, 0, Zn3,
	// XY  =   0.0f, XZ  =   0.0, YZ  =   0.0;
	F32_opMov,     const_F0_0, 0, XY,
	F32_opMov,     const_F0_0, 0, XZ,
	F32_opMov,     const_F0_0, 0, YZ,
	// X2Y =   0.0f, X2Z =   0.0, Y2X =   0.0;
	F32_opMov,     const_F0_0, 0, X2Y,
	F32_opMov,     const_F0_0, 0, X2Z,
	F32_opMov,     const_F0_0, 0, Y2X,
	// Y2Z =   0.0f, Z2X =   0.0, Z2Y =   0.0;
	F32_opMov,     const_F0_0, 0, Y2Z,
	F32_opMov,     const_F0_0, 0, Z2X,
	F32_opMov,     const_F0_0, 0, Z2Y,
	// compassPointCount = 0.0f;
	F32_opMov,     const_F0_0, 0, compassPointCount,
	0,0,0,0
